sensors = [
    ### WIA sensors ###
    {"type":'WIA_TYPE', "name":'dev_2AeeY8az', "serial_number":'a81758fffe075601',
        "number": 1, "area":'Stokes Building', "room":'1.1', "longitude":None, "latitude":None, "altitude":None},       
    {"type":'WIA_TYPE', "name":'dev_5ipjjl7t', "serial_number":'a81758fffe075602',
        "number": 2, "area":'Business School', "room":'1.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_GghFIehA', "serial_number":'A81758FFFE0755CE',
        "number": 3, "area":'Stokes Building', "room":'1.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_OhjroeDo', "serial_number":'a81758fffe0755cf',
        "number": 4, "area":'Stokes Building', "room":'1.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_1f43VXgG', "serial_number":'A81758FFFE0755D0',
        "number": 5, "area":'Stokes Building', "room":'1.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_klkV9Q10', "serial_number":'A81758FFFE0755D1',
        "number": 6, "area":'Stokes Building', "room":'1.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_KJUzlDMX', "serial_number":'A81758FFFE0755D2',
        "number": 7, "area":'Stokes Building', "room":'1.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_ih8zqoVx', "serial_number":'A81758FFFE0755D3',
        "number": 8, "area":'Sports Complex', "room":'1.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_NTBAKp18', "serial_number":'A81758FFFE0755D4',
        "number": 9, "area":'Sports Complex', "room":'1.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_nCa4IhPZ', "serial_number":'A81758FFFE0755D5',
        "number":10, "area":'Stokes Building', "room":'1.3', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'WIA_TYPE', "name":'dev_IFrFM8jy', "serial_number":'A81758FFFE0755D6',
        "number":11, "area":'Marconi Building', "room":'2.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_zjR3ikUA', "serial_number":'A81758FFFE0755E0',
        "number":12, "area":'Stokes Building', "room":'2.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_LipbyoZC', "serial_number":'A81758FFFE0755E1',
        "number":13, "area":'Stokes Building', "room":'2.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_dyYjbjxN', "serial_number":'A81758FFFE0755E2',
        "number":14, "area":'Stokes Building', "room":'2.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_QBS9qghx', "serial_number":'A81758FFFE0755E3',
        "number":15, "area":'Stokes Building', "room":'2.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_v7OY9OUn', "serial_number":'A81758FFFE0755E4',
        "number":16, "area":'Stokes Building', "room":'2.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_YqSewUO7', "serial_number":'A81758FFFE0755E5',
        "number":17, "area":'Stokes Building', "room":'2.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_FEcXof01', "serial_number":'A81758FFFE0755E6',
        "number":18, "area":'Stokes Building', "room":'2.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_QfSC8mBU', "serial_number":'A81758FFFE0755E7',
        "number":19, "area":'Stokes Building', "room":'2.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_cKoWgXyj', "serial_number":'A81758FFFE0755E8',
        "number":20, "area":'Stokes Building', "room":'2.3', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'WIA_TYPE', "name":'dev_pfAy57h7', "serial_number":'A81758FFFE0755F4',
        "number":21, "area":'Stokes Building', "room":'3.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_N7H0SBgT', "serial_number":'A81758FFFE079972',
        "number":22, "area":'Stokes Building', "room":'3.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_5g16G9fy', "serial_number":'A81758FFFE079973',
        "number":23, "area":'Marconi Building', "room":'3.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_UQIoz5Qx', "serial_number":'A81758FFFE079984',
        "number":24, "area":'Marconi Building', "room":'3.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_kmbnc9Gx', "serial_number":'A81758FFFE079985',
        "number":25, "area":'Stokes Building', "room":'3.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_FkqHLlhJ', "serial_number":'A81758FFFE079986',
        "number":26, "area":'Stokes Building', "room":'3.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_cmCdaQS2', "serial_number":'A81758FFFE079987',
        "number":27, "area":'Stokes Building', "room":'3.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_uMU13Isr', "serial_number":'A81758FFFE079988',
        "number":28, "area":'Marconi Building', "room":'3.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_J2Rc8d8D', "serial_number":'A81758FFFE079989',
        "number":29, "area":'Stokes Building', "room":'3.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_yF8AiCIR', "serial_number":'A81758FFFE07998A',
        "number":30, "area":'Stokes Building', "room":'3.3', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'WIA_TYPE', "name":'dev_gh5EA2kb', "serial_number":'A81758FFFE07998B',
        "number":31, "area":'Stokes Building', "room":'4.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_HzG5SQCI', "serial_number":'A81758FFFE07998C',
        "number":32, "area":'Stokes Building', "room":'4.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_llf3XBxH', "serial_number":'A81758FFFE0799BA',
        "number":33, "area":'Stokes Building', "room":'4.1', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_6gEjAkdk', "serial_number":'A81758FFFE0799BB',
        "number":34, "area":'Stokes Building', "room":'4.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_MPQhIhMR', "serial_number":'A81758FFFE0799BC',
        "number":35, "area":'Stokes Building', "room":'4.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_XuFA1rtJ', "serial_number":'A81758FFFE0799BD',
        "number":36, "area":'Stokes Building', "room":'4.2', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_v1S12Qq9', "serial_number":'A81758FFFE0799BE',
        "number":37, "area":'Stokes Building', "room":'4.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_3RRijRNM', "serial_number":'A81758FFFE0799BF',
        "number":38, "area":'Stokes Building', "room":'4.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_FunZYSTq', "serial_number":'A81758FFFE0799C0',
        "number":39, "area":'Sports Complex', "room":'4.3', "longitude":None, "latitude":None, "altitude":None},
    {"type":'WIA_TYPE', "name":'dev_vBV8IpbD', "serial_number":'A81758FFFE0799C1',
        "number":40, "area":'Marconi Building', "room":'4.3', "longitude":None, "latitude":None, "altitude":None},            

    ### HIDATA sensors ###
    {"type":'HIDATA_TYPE', "name":'SA105', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'HIDATA_TYPE', "name":'SA301', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    
    ### CIVIC sensors ###
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},


    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 0 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 1 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 2 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 3 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 4 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 5 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 6 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 7 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 8 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - PEDESTRIAN', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - BIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - CAR', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'CIVIC_TYPE', "name":'Zone 9 - DCU Entrance - Ballymun Road - UNDEFINED', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},


    ### 4DA WIA sensors ###
    {"type":'4DA_WIA_TYPE', "name":'1', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'2', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'3', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'4', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'5', "serial_number":None,
        "number":None, "area":"Stokes building", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'6', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'7', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'8', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'9', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'10', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'4DA_WIA_TYPE', "name":'11', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'12', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'13', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'14', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'15', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'16', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'17', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'18', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'19', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'20', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'4DA_WIA_TYPE', "name":'21', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'22', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'23', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'24', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'25', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'26', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'27', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'28', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'29', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'30', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    
    {"type":'4DA_WIA_TYPE', "name":'31', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'32', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'33', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'34', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'35', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'36', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'37', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'38', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'39', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_WIA_TYPE', "name":'40', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    ### 4DA BBB sensors ###
    {"type":'4DA_BBB_TYPE', "name":'DCU - Londis - General Waste & Pizza Belly - TRASH', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - Londis - General Waste & Pizza Belly - BOTTLE_CANS', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - Londis - General Waste & Pizza Belly - COMPOSTABLES', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - Londis - General Waste & Pizza Belly - PAPER', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - New Paved Picnic Plaza Next To Albert College - BOTTLE_CANS', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - New Paved Picnic Plaza Next To Albert College - TRASH', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_BBB_TYPE', "name":'DCU - New Paved Picnic Plaza Next To Albert College - COMPOSTABLES', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    
    ### 4DA CIVIC sensors ###
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 0 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 1 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 2 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":'Marconi Building', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 3 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 4 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - LONG TRUCK', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - MOTORBIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - SHORT TRUCK', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - CAR', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 5 - DCU Main Entrance - UNDEFINED', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 6 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 7 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 8 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},

    {"type":'4DA_CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - PEDESTRIAN', "serial_number":None,
        "number":None, "area":'Sports Complex', "room":'505', "longitude":None, "latitude":None, "altitude":None},
    {"type":'4DA_CIVIC_TYPE', "name":'Zone 9 - DCU Main Entrance - BIKE', "serial_number":None,
        "number":None, "area":"Business School", "room":'505', "longitude":None, "latitude":None, "altitude":None},
]
